### ISSUE TITLE
Seems completely broken on Ember >2

### ISSUE THREAD

**Issue by constantm** [bdvholmes/ember-cli-mapbox#10]
Getting errors in the initialiser [here](https://github.com/bdvholmes/ember-cli-mapbox/blob/master/addon/initializers/mapbox-access-code.js#L2).

**Comment by planetexpress69** [comment]
Same here. Any chance to get that fixed?

**Comment by constantm** [comment]
Looking at his public activity, @bdvholmes has disappeared from Github. :D

**Comment by planetexpress69** [comment]
Hi @constantm ,

consider to hack the component's initializer like so:

```javascript
export function initialize(application) {
  L.mapbox.accessToken =  '<yourtokenhere>';
}
export default {
  name: 'mapbox-access-code',
  initialize: initialize,
};
```

**Comment by constantm** [comment]
Thanks @planetexpress69, I'll give it a go. Currently I'm just still using 1.13.x - very much still learning Ember, and didn't currently have the time to try and figure out how initialisers work in 2.x.

**Comment by planetexpress69** [comment]
Its my 3rd week of ember. What a confusing world where everything changes after... a week or so? Would suggest not to stick on older version, nevertheless.

**Comment by constantm** [comment]
Haha you've obviously been making better progress than I have. I've been dabbling for months, and it seems that things are starting to calm down a bit. As far as I understand, 1.13.x is not as much an old version, as it is 2.x with all the deprecated code still in place, giving some libraries (like this one) a longer runway to change over.

**Comment by planetexpress69** [comment]
Well, the app I am trying to build is fairly simple. I stuck a whole week on authentication and adapter/serializer to fetch some data from a Django API into Ember Data models... It slowly gets better but I still spend ages on reading stuff. Well not reading actually... I spend hours finding stuff not (yet?) deprecated. By the way: This seems to be a good way to get the config object.

```javascript
let config = this.container.lookupFactory('config:environment');
```

**Comment by bdvholmes** [comment]
@constantm @planetexpress69 most definitely still here :grin:

Glad to hear you're trying it with 2.x, @planetexpress69 would you like to submit a pull request with that line change and I'll deploy a 2.x compatible version :-)

If either of you are interested in owning fully upgrading this to 2.x I'd be happy to help you along the way.
