### ISSUE TITLE
Uncaught TypeError: window.XDomainRequest is not a function from corslite.js

### ISSUE THREAD

**Issue by constantm** [bdvholmes/ember-cli-mapbox#2]
This probably isn't an issue directly related to this addon, but I'm not sure where to start looking for what's causing the issue. It looks like it's raised by corslite.js, but I can't figure out if this file is used exclusively by this addon, or whether it's a new mapbox addition. I'm running Ember 1.13.8. Any ideas?

**Comment by bdvholmes** [comment]
Hey, @constantm. Are you still getting this issue, do you think you could post me a stack trace?

**Comment by constantm** [comment]
I am indeed. I tracked in down to Pretender.js, used by ember-cli-mirage, which overwrites XMLHttpRequest. More details here: https://github.com/pretenderjs/pretender/issues/112

**Comment by bdvholmes** [comment]
Good to know (I love that it's called corslite). I know that @samselikoff is putting some work into getting mirage to work with CORS.

Let me know if you have any feature requests for ember-cli-mapbox, the current functionality is relatively basic but I can build stuff out quickly.
