### ISSUE TITLE
Can't get very simple map-markers to work?

### ISSUE THREAD

**Issue by constantm** [bdvholmes/ember-cli-mapbox#5]
I'm trying to get map markers to work with no luck. Any ideas what I might be missing here?

```
{{#mapbox-map mapId='constantlm.cgqjpdfg' center=(mapbox-coords 37.768 -122.381) zoom=2 divId=(opportunity-map-slug model.slug) as |map|}}
      {{#each model.opportunityLocations as |location|}}
        {{mapbox-marker map=map coordinates=(mapbox-coords location.latitude location.longitude)}}
      {{/each}}
{{/mapbox-map}}
```

which results in:

`Uncaught TypeError: Cannot read property 'addLayer' of undefined`

**Comment by constantm** [comment]
After some more digging, it looks like `didInsertElement` does not fire when `mapbox-map` has child components/markers. When removing the markers however, it does fire. This happens on Ember 1.13.8.

**Comment by bdvholmes** [comment]
@constantm sorry for not seeing this earlier. Thanks for investigating :smile:
